/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.md5;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.security.MessageDigest;
import javax.swing.JOptionPane;

/**
 *
 * @author honha
 */
public class frm_MD5 extends javax.swing.JFrame {

    /**
     * Creates new form frm_MD5
     */
    public frm_MD5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btndangnhap = new javax.swing.JButton();
        btndangky = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        txtrs1 = new javax.swing.JTextField();
        txtchuoi = new javax.swing.JTextField();
        txtrs2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HASH MD5");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Result 1:");

        jLabel5.setText("Result 2:");

        jLabel6.setText("Chuỗi: Username + Pass");

        btndangnhap.setText("Đăng nhập");
        btndangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangnhapActionPerformed(evt);
            }
        });

        btndangky.setText("Đăng ký");
        btndangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangkyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtusername)
                            .addComponent(txtpass)
                            .addComponent(txtrs2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrs1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtchuoi)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btndangnhap)
                                        .addGap(85, 85, 85)
                                        .addComponent(btndangky)))
                                .addGap(16, 16, 16)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtrs1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtrs2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtchuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndangnhap)
                    .addComponent(btndangky))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    public  boolean kiemTraMatKhau(String matKhau) {
//    if (matKhau.length() < 8) {
//        JOptionPane.showMessageDialog(null,"Mật khẩu phải có ít nhất 8 ký tự!");
//        return false;
//    }
//    boolean hasUpperCase = false;
//    boolean hasNumber = false;
//    boolean hasSpecialChar = false;
//    for (char c : matKhau.toCharArray()) {
//        if (Character.isUpperCase(c)) {
//            hasUpperCase = true;
//        } else if (Character.isDigit(c)) {
//            hasNumber = true;
//        } else if (Character.isLetterOrDigit(c) ) {
//            hasSpecialChar = true;
//        }
//        
//    }
//    if (!hasUpperCase) {
//        JOptionPane.showMessageDialog(null,"Mật khẩu phải có ít nhất 1 ký tự in hoa!");
//        return false;
//    }
//    if (!hasNumber) {
//       JOptionPane.showMessageDialog(null,"Mật khẩu phải có ít nhất 1 số!");
//        return false;
//    }
//    if (!hasSpecialChar) {
//         JOptionPane.showMessageDialog(null,"Mật khẩu phải có ít nhất 1 ký tự đặc biệt!");
//        return false;
//    }
//    return true;
//}
    private void btndangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangkyActionPerformed
        try{
            
        
        String user = txtusername.getText();
        
        String pass = txtpass.getText();
if(pass.length()<8){
    JOptionPane.showMessageDialog(null,"Mật khẩu phải có ít nhất 8 ký tự!");
}
        boolean hasUpperCase = false;
    boolean hasNumber = false;
    boolean hasSpecialChar = false;
        for (char c : pass.toCharArray()) {
        if (Character.isUpperCase(c)) {
            hasUpperCase = true;
        } else if (Character.isDigit(c)) {
            hasNumber = true;
        } else if (!Character.isLetterOrDigit(c)) {
            hasSpecialChar = true;
        }
        
    }
       

// Nếu mật khẩu hợp lệ
if(!(hasUpperCase&&hasNumber&&hasSpecialChar)){
     JOptionPane.showMessageDialog(null,"Mật khẩu phải có ít nhất 1 ký tự in hoa!, 1 kỳ tự số!, 1 ký tự đặc biệt  ");
     return;
}
    String bam = "";
     bam = user + pass;
        MessageDigest md = MessageDigest.getInstance("MD5");
        md.update(bam.getBytes());
        byte[] byteData = md.digest();
        StringBuffer sb = new StringBuffer();
        for(int i= 0; i<byteData.length;i++){
            sb.append(Integer.toString((byteData[i]&0xff)+0x100,16).substring(1));
            
        }
        System.out.println("Digest(in hex format)::"+sb.toString());
        txtrs1.setText(sb.toString());
        StringBuffer hexString = new StringBuffer();
        for(int i= 0; i<byteData.length;i++){
            String hex = Integer.toHexString(0xff & byteData[i]);
            if(hex.length() ==1){
                hexString.append('0');
            }
            hexString.append(hex);
            
        }
        System.out.println("Digest(in hex format)::"+hexString.toString());
        txtrs2.setText(hexString.toString());
        txtchuoi.setText(bam.toString());
        BufferedWriter bw = null;
        String filename= "D:\\Bammd5.txt";
        bw= new BufferedWriter(new FileWriter(filename));
        bw.write(hexString.toString());
        bw.close();
        JOptionPane.showMessageDialog(null, "Bạn đã đăng ký thành công. Vui lòng đăng nhập lại");
        }
        catch(Exception ex){
            System.out.println("Loi bam username va pass:" +ex);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btndangkyActionPerformed

    private void btndangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangnhapActionPerformed
        
            
        
        String user = txtusername.getText();
        String pass = txtpass.getText();
        String bam = "";
        bam= user+pass;
        BufferedReader br = null;
        String filename = "D:\\Bammd5.txt";
        try{
            br= new BufferedReader(new FileReader(filename));
            StringBuffer sb = new StringBuffer();
            char[] ca= new char[5];
            while(br.ready()){
                int len = br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("chung thuc :"+""+sb);
            String chuoi = sb.toString();
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(bam.getBytes());
            byte[] byteData = md.digest();
            StringBuffer hexString = new StringBuffer();
            for(int i= 0 ; i < byteData.length ;i++){
                String hex = Integer.toHexString(0xff & byteData[i]);
                if(hex.length() == 1){
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            
            System.out.println("Bam username va password: " + " " + hexString.toString());
            Boolean k = hexString.toString().equals(chuoi);
            if(k==true){
                JOptionPane.showMessageDialog(null, "Đăng nhập thành công !");
                
                txtrs1.setText(hexString.toString());
                txtrs2.setText(chuoi);
                txtchuoi.setText("Username: " + user + "Password: " + pass);
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Đăng nhập thất bại !");
            }
                
        }catch(Exception ex){
             System.out.println("Loi dang nhap: " + ex);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btndangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_MD5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_MD5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_MD5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_MD5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_MD5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangky;
    private javax.swing.JButton btndangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtchuoi;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtrs1;
    private javax.swing.JTextField txtrs2;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
