
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;

import javax.crypto.spec.DHParameterSpec;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nguye
 */
public class BHT5 extends javax.swing.JFrame {

    /**
     * Creates new form BHT5
     */
        KeyAgreement aliceKeyAgree;
        PublicKey bobPubKey;
        SecretKey aliceDesKey;
        Cipher aliceCipher;
    public BHT5() {
        initComponents();
    }
    public static final String toHexString (byte [] block)
    {
        StringBuffer buf=new StringBuffer();
        int len=block.length;
        for(int i=0;i<len;i++)
        {
            byte2hex(block[i],buf);
            if(i<len-1)
            {
                buf.append(":");
            }
        }
        return buf.toString();
    }
    
    public static final void byte2hex(byte b,StringBuffer buf)
    {
        char[] hexChars={'0','1','2','3',
                        '4','5','6','7',
                        '8','9','A','B',
                        'C','D','E','F'};
        int high = ((b&0xf0)>>4);
        int low = (b&0x0f);
        buf.append(hexChars[high]);
        buf.append(hexChars[low]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnmahoagiaima = new javax.swing.JButton();
        btntaokhoaA = new javax.swing.JButton();
        txtkhoakab = new javax.swing.JTextField();
        txtkhoabob = new javax.swing.JTextField();
        txtkhoaalice = new javax.swing.JTextField();
        txtmahoakab = new javax.swing.JTextField();
        btnmahoakab = new javax.swing.JButton();
        btbkhoachung = new javax.swing.JButton();
        btnhienthiKB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alice");

        jLabel2.setText("Khóa Alice:");

        jLabel3.setText("Khoa BoB:");

        jLabel4.setText("Khóa KAB:");

        jLabel5.setText("Mã hóa KAB:");

        btnmahoagiaima.setText("Mã hóa/Giải mã");
        btnmahoagiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoagiaimaActionPerformed(evt);
            }
        });

        btntaokhoaA.setText("Tạo khóa A");
        btntaokhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaokhoaAActionPerformed(evt);
            }
        });

        txtkhoabob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkhoabobActionPerformed(evt);
            }
        });

        txtkhoaalice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkhoaaliceActionPerformed(evt);
            }
        });

        btnmahoakab.setText("Mã hóa KAB");
        btnmahoakab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoakabActionPerformed(evt);
            }
        });

        btbkhoachung.setText("Khóa chung");
        btbkhoachung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbkhoachungActionPerformed(evt);
            }
        });

        btnhienthiKB.setText("Hiển thị KB");
        btnhienthiKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienthiKBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtkhoaalice, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(btntaokhoaA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtmahoakab, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnmahoakab, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkhoakab, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkhoabob, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnhienthiKB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btbkhoachung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnmahoagiaima, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkhoaalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btntaokhoaA))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkhoabob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhienthiKB))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkhoakab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbkhoachung))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmahoakab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmahoakab))
                .addGap(56, 56, 56)
                .addComponent(btnmahoagiaima)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkhoaaliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkhoaaliceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhoaaliceActionPerformed

    private void btntaokhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaokhoaAActionPerformed
         //TODO add your handling code here:
        try{
            AlgorithmParameterGenerator paramGen=AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params = paramGen.generateParameters();
            DHParameterSpec dhSkipParamSpec=
                    (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);
            System.out.println("Generrating a DH KeyPair...");
            KeyPairGenerator aliceKpairGen=KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKpair = aliceKpairGen.generateKeyPair();
            
            System.out.println("Initalizing the KeyAgreement Engine with DH private key");
            aliceKeyAgree= KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());
            
            byte[] alicePubKeyEnc=aliceKpair.getPublic().getEncoded();
            FileOutputStream fos=new FileOutputStream("D:/A.pub");
            fos.write(alicePubKeyEnc);
            fos.close();
            txtkhoaalice.setText(alicePubKeyEnc.toString());

        }catch(Exception ex){}
    }//GEN-LAST:event_btntaokhoaAActionPerformed

    private void btnmahoakabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoakabActionPerformed
        // TODO add your handling code here:
        try
        {
            aliceKeyAgree.doPhase(bobPubKey,true);
            aliceDesKey = aliceKeyAgree.generateSecret("DES");
            txtmahoakab.setText(aliceDesKey.toString());
            
            BufferedWriter bw= null;
            String fileName ="D:\\KhoaA.txt";
            bw=new BufferedWriter (new FileWriter(fileName));
            bw.write(aliceDesKey.toString());
            bw.close();
        }catch(Exception ex){}
    }//GEN-LAST:event_btnmahoakabActionPerformed

    private void btbkhoachungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbkhoachungActionPerformed
        // TODO add your handling code here:
         try{
            FileInputStream fis= new FileInputStream("D:/B.pub");
            byte[] bobPubKeyEnc=new byte[fis.available()];
            fis.read(bobPubKeyEnc);
            fis.close();
            
            KeyFactory aliceKeyFac= KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec=new X509EncodedKeySpec(bobPubKeyEnc);
            bobPubKey=aliceKeyFac.generatePublic( x509KeySpec);
             System.out.println("Executing PHASE1 of key agreement...");
             aliceKeyAgree.doPhase(bobPubKey,true);
             byte [] aliceSharedSecret= aliceKeyAgree.generateSecret();
             
             System.out.println("Khoa chung: secret (DEBUG ONLY):"+CryptoUtil.toHexString(aliceSharedSecret));
             txtkhoakab.setText(CryptoUtil.toHexString(aliceSharedSecret));
             
        }catch(Exception ex){}
    }//GEN-LAST:event_btbkhoachungActionPerformed

    private void btnhienthiKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienthiKBActionPerformed
        // TODO add your handling code here:
            try{
            FileInputStream fis= new FileInputStream("D:/B.pub");
            byte[] bKeyP=new byte[fis.available()];
            fis.read(bKeyP);
            fis.close();
            txtkhoabob.setText(bKeyP.toString());
        }catch(Exception ex){ }
    }//GEN-LAST:event_btnhienthiKBActionPerformed

    private void txtkhoabobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkhoabobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhoabobActionPerformed

    private void btnmahoagiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoagiaimaActionPerformed
        // TODO add your handling code here:
        DESCS des =new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btnmahoagiaimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BHT5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BHT5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BHT5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BHT5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BHT5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbkhoachung;
    private javax.swing.JButton btnhienthiKB;
    private javax.swing.JButton btnmahoagiaima;
    private javax.swing.JButton btnmahoakab;
    private javax.swing.JButton btntaokhoaA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtkhoaalice;
    private javax.swing.JTextField txtkhoabob;
    private javax.swing.JTextField txtkhoakab;
    private javax.swing.JTextField txtmahoakab;
    // End of variables declaration//GEN-END:variables
}
